### ISSUE TITLE
Blank images on https localhost

### ISSUE THREAD

**Issue by wiinci** [typicode/tlapse#12]
Running `tlapse --every 45s --directory ./screens -- https://localhost:8080` gives:

```bash
Screenshots directory: ./screens
Interval: 45s
10:42:32 ✔ Generated 1 screenshot from 1 url and 1 size
```

And a 6kb blank image: 
![1514950948121](https://user-images.githubusercontent.com/505739/34508579-1d3b7f8a-f00f-11e7-98e4-2edd02ee3465.png)

**Comment by keevvinc** [comment]
Why would your localhost be https?

**Comment by willnode** [comment]
I also have the same problem. But my case is won't execute the javascript that renders the page (Vue, in my case).

It looks like screenshot won't work for any page that uses frameworks 🤔

**Comment by wiinci** [comment]
@keevvinc alright, moved it to plain `http`, and still seeing nothing but a blank 6kb image:

```bash
tlapse -d ./screens -e 30s -- http://localhost:8080
Screenshots directory: ./screens
Interval: 30s
03:09:12 ✔ Generated 1 screenshot from 1 url and 1 size
03:09:47 ○ Duplicate screenshot, skipping
```

Just like @willnode, mine is also a VueJS project.

**Comment by typicode** [comment]
Hmm, could you try delaying the capture?
https://github.com/sindresorhus/pageres-cli#-d---delaynumber

```
tlapse -d ./screens -e 30s -- http://localhost:8080 --delay=3
```

**Comment by keevvinc** [comment]
@wiinci I did not mean it would solve your problem, I was just curious why you use https on localhost. 🙂

**Comment by wiinci** [comment]
@typicode no luck with `--delay=3` … still getting the same blank image 😢

**Comment by kumamaki** [comment]
Me too. I'm also using VueJS.

**Comment by typicode** [comment]
It may work better with `v1.0.0`, as tlapse now uses Puppeteer instead of PhantomJS (see @gasp PR https://github.com/typicode/tlapse/pull/15).
