### ISSUE TITLE
Can we specify which browser / resolution to use?

### ISSUE THREAD

**Issue by keevvinc** [typicode/tlapse#13]
I get different results in browser and on screenshot.

**Comment by typicode** [comment]
Hi @keevvinc,

I don't think it's possible to specify a browser, as `pageres-cli` is using PhantomJS.
But the resolution, yes (https://github.com/typicode/tlapse#options):

```
tlapse -- localhost:3000 1024x768
```

See https://github.com/sindresorhus/pageres-cli#usage for additional options.

Hmm, if you get different results, maybe you should check `pageres-cli` docs/issues, as `tlapse` is just a wrapper around it.
